# Generated by Django 2.2.1 on 2019-06-25 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery_items',
            name='expiry_date',
        ),
    ]
